#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
echo "$script_dir"

filter="$1"

echo "Run: dir $script_dir -- filter \"$filter\""

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
filter="$1"

cd $script_dir
scripts=$(find runs -maxdepth 1 -mindepth 1 -executable -type f)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        echo "filtered: $filter -- $script"
        continue
    fi
    ./$script
done
