#!/usr/bin/env bash

git clone git@github.com:neovim/neovim.git ~/workspace/neovim
cd ~/workspace/neovim
git fetch
git checkout v0.12.5

sudo apt install cmake gettext lua5.1 liblua5.1-0-dev
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
